name: chat_example
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  # firebase_messaging: 13.0.0
  # flutter_local_notifications: 9.8.0+1
  google_sign_in: ^5.2.4
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+9
  shared_preferences: ^2.0.13
  intl: ^0.18.0
  photo_view: ^0.14.0
  provider: ^6.0.2
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.20
  equatable: ^2.0.3
  google_sign_in_web: ^0.10.0+5
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^8.2.0

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
