// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYUY8bsW7J145EVKXBDCExVhxTvlVRwYI',
    appId: '1:762607077577:web:ec8b38a19e4a494d8ce518',
    messagingSenderId: '762607077577',
    projectId: 'fluttertest-93c78',
    authDomain: 'fluttertest-93c78.firebaseapp.com',
    databaseURL: 'https://fluttertest-93c78-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-93c78.appspot.com',
    measurementId: 'G-71J4SKVS5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7hAxOkkD2ZdOZ5N-n1v-KH9GEYUNDhk',
    appId: '1:762607077577:android:95c5a92ea12db9dc8ce518',
    messagingSenderId: '762607077577',
    projectId: 'fluttertest-93c78',
    databaseURL: 'https://fluttertest-93c78-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-93c78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM32zQzBumXLjLFHu1pGHhARxZYyAtGmg',
    appId: '1:762607077577:ios:31865ecc174b007f8ce518',
    messagingSenderId: '762607077577',
    projectId: 'fluttertest-93c78',
    databaseURL: 'https://fluttertest-93c78-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-93c78.appspot.com',
    iosClientId: '762607077577-6oqdd7ktl8c46n1nm92mgrd0q0tmqm78.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM32zQzBumXLjLFHu1pGHhARxZYyAtGmg',
    appId: '1:762607077577:ios:31865ecc174b007f8ce518',
    messagingSenderId: '762607077577',
    projectId: 'fluttertest-93c78',
    databaseURL: 'https://fluttertest-93c78-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-93c78.appspot.com',
    iosClientId: '762607077577-6oqdd7ktl8c46n1nm92mgrd0q0tmqm78.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatExample',
  );
}
